import '@/styles/client/room-type.scss';
export const metadata = {
  title: 'VDORM | Phòng',
  description: 'Generated by Next.js',
};

export default function RoomTypeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
