import '@/styles/client/about-us.scss';
export const metadata = {
  title: 'VDORM | Về chúng tôi',
  description: 'Generated by Next.js',
};

export default function AboutUsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
