import '@/styles/client/instruction.scss';
export const metadata = {
  title: 'VDORM | Hướng dẫn',
  description: 'Generated by Next.js',
};

export default function InstructionLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
