import '@/styles/client/room-register.scss';

export const metadata = {
  title: 'VDORM | Đăng ký phòng',
  description: 'Generated by Next.js',
};

export default function RoomRegisterLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
