import '@/styles/client/news.scss';
import '@/styles/client/news-details.scss';

export const metadata = {
  title: 'VDORM | Tin tức',
  description: 'Generated by Next.js',
};

export default function NewsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
