import '@/styles/client/services.scss';

export const metadata = {
  title: 'VDORM | Dịch vụ',
  description: 'Generated by Next.js',
};

export default function ServicesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
